packages:
  - 'apps/*'

overrides:
  '@nestjs/swagger>js-yaml': 5.2.2
  fast-uri: 3.1.5

allowBuilds:
  '@scarf/scarf': false
  cpu-features: false
  msgpackr-extract: false
  protobufjs: false
  ssh2: false
